Add Requires(pretrans) dependency testcases in pytests
vmware/tdnf pull request #170
Opened 2020-09-09 10:01 UTC by keerthanakalyan

2020-09-09 10:11 UTC, cbsiddharth approved these changes
LGTM.

2020-09-09 10:11 UTC, cbsiddharth commented on pytests/conftest.py
> +        capture = re.search(r'Error\((\d+)\) :', stderr)
Regex should be the same: `r'^Error\((\d+)\) :'` as we still expect Error to be in the beginning of a newline.

2020-09-09 13:46 UTC, tapakund approved these changes

2020-09-09 14:49 UTC, cbsiddharth approved these changes

2020-09-14 06:22 UTC, merged

2020-09-14 06:22 UTC, sshedi requested changes

2020-09-14 06:22 UTC, sshedi commented on pytests/tests/test_pretrans.py
> +def teardown_test(utils):
Please erase all the packages installed by this script as a part of cleanup. Apart from this, LGTM