ignore unset pTdnf->pArgs in TDNFRefresh()
vmware/tdnf pull request #222
Opened 2021-02-05 18:11 UTC by oliverkurth

As requested by @shreyasbe , this is to fix pmd.

2021-02-06 14:32 UTC, sshedi requested changes

2021-02-06 14:32 UTC, sshedi commented on client/init.c
> +    if (pTdnf->pArgs)
Please validate pTdnf & pTdnf->pSack.

2021-02-06 14:32 UTC, sshedi commented on client/init.c
> +    else
else is redundant here.

2021-02-10 01:35 UTC, oliverkurth commented
So looks like I broke the API with PR206 - it caused the TDNFRefresh() call to be made in the client (!), and this of course failed. I now moved the calls to `TDNFRefresh()` to client/api.c where they belong. This makes the calls to be made by the server. Similarly, the call to `TDNFAddCmdLinePackages()` had to be moved.

I tested this various invocations of `pmd-cli` when built with these changes and they looked okay. The `pmd-cli pkg check` command segfaults, but I believe this was broken before. @tapakund , please rebuild pmd with these changes and test thoroughly.

2021-02-10 05:10 UTC, jaankit commented
> So looks like I broke the API with PR206 - it caused the TDNFRefresh() call to be made in the client (!), and this of course failed. I now moved the calls to `TDNFRefresh()` to client/api.c where they belong. This makes the calls to be made by the server. Similarly, the call to `TDNFAddCmdLinePackages()` had to be moved.
> 
> I tested this various invocations of `pmd-cli` when built with these changes and they looked okay. The `pmd-cli pkg check` command segfaults, but I believe this was broken before. @tapakund , please rebuild pmd with these changes and test thoroughly.

"pmd-cli pkg check" is failing because corresponding API is not implemented(pkg_invoke_check()) in pmd when it gets called from tdnf but "check" is added in cmdlist at here: https://github.com/vmware/pmd/blob/1ffd119b8831829b30714e3efd6ad48b86c93c9f/tools/cli/pkgmgmt/pkg_main.c#L29 . Thus, it is crashing. This need to be fixed in pmd. This issue was present in old version of pmd also.

Tested some of the command with this change. Works fine. Thorough testing is in progress.

2021-02-12 04:17 UTC, tapakund requested changes
All other changes looks fine.

2021-02-12 04:17 UTC, tapakund commented on client/init.c
> +    if (!pTdnf->pArgs)
Can we modify this function to:
uint32_t
TDNFRefresh(
    PTDNF pTdnf)
{
    uint32_t dwError = 0;
    if(!pTdnf || !pTdnf->pSack || !pTdnf->pArgs)
    {
        dwError = ERROR_TDNF_INVALID_PARAMETER;
        return dwError;
    }
    return TDNFRefreshSack(pTdnf, pTdnf->pSack, pTdnf->pArgs->nRefresh);
}

2021-02-18 22:54 UTC, oliverkurth commented on client/init.c
> +    if (!pTdnf->pArgs)
Done.

2021-02-19 02:34 UTC, merged