use TDNFJoin() to construct paths
vmware/tdnf pull request #264
Opened 2021-10-25 21:24 UTC by oliverkurth

This adds the `TDNFJoin()` function to create directory paths.

2021-10-26 15:09 UTC, sshedi requested changes

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +    for(pszNode = va_arg(ap, char *); pszNode; pszNode = va_arg(ap, char *))
if this loop is for counting number of va args, then it doesn't work.
get rid of next for loop (at line 795) and process args one by one withing this loop.

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +            nAbsolute = 1;
nit: do pszNodeTmp++ here, saves one iteration :)

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +        while(*pszNodeTmp == '/') pszNodeTmp++;
User strspn instead.

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +        pszTmp = pszNodeTmp + strlen(pszNodeTmp) - 1;
store `strlen(pszNodeTmp)` in a variable. it's again used in line 813

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +        strcpy(pszTmp, ppszNodes[i]);
Use strcat here?

2021-10-26 15:09 UTC, sshedi commented on common/utils.c
> +        nLength += strlen(pszNodeTmp) + 1;
you can just keep appending path to a resultant buffer upon every iteration and reallocate memory as needed.

2021-10-28 21:48 UTC, oliverkurth commented on common/utils.c
> +            nAbsolute = 1;
Thx - even better, I need the `while` loop only if the condition is true.

2021-10-28 21:50 UTC, oliverkurth commented on common/utils.c
> +        while(*pszNodeTmp == '/') pszNodeTmp++;
That's not making the code any more readable or efficient.

2021-10-28 21:54 UTC, oliverkurth commented on common/utils.c
> +        pszTmp = pszNodeTmp + strlen(pszNodeTmp) - 1;
Thx! Done.

2021-10-28 22:47 UTC, oliverkurth commented on common/utils.c
> +    for(pszNode = va_arg(ap, char *); pszNode; pszNode = va_arg(ap, char *))
Last arg must be `NULL`. As discussed this internally.

2021-10-28 22:48 UTC, oliverkurth commented on common/utils.c
> +        strcpy(pszTmp, ppszNodes[i]);
Done.

2021-10-29 00:14 UTC, oliverkurth commented on common/utils.c
> +        nLength += strlen(pszNodeTmp) + 1;
Done.

2021-11-25 06:59 UTC, sshedi approved these changes
LGTM. One improvement I can think of is, if given an absolute path call NormalizePath function and use the return value as is.

2021-11-29 18:50 UTC, oliverkurth commented
Build failure is unrelated: Photon 4.0 updated to openssl 3.0.0. Possible fix:
```
diff --git a/client/remoterepo.c b/client/remoterepo.c
index 22c870e..e53d0d6 100644
--- a/client/remoterepo.c
+++ b/client/remoterepo.c
@@ -170,9 +170,13 @@ TDNFGetDigestForFile(
     {
         pr_err("Digest Init Failed\n");
         dwError = ERROR_TDNF_CHECKSUM_VALIDATION_FAILED;
-        /*MD5 is not approved in FIPS mode. So, overrriding
-          the dwError to show the right error to the user */
+        /* MD5 is not approved in FIPS mode. So, overrriding
+           the dwError to show the right error to the user */
+#if defined(OPENSSL_VERSION_MAJOR) && (OPENSSL_VERSION_MAJOR >= 3)
+        if (EVP_default_properties_is_fips_enabled(NULL) && !strcasecmp(hash->hash_type, "md5"))
+#else
         if (FIPS_mode() && !strcasecmp(hash->hash_type, "md5"))
+#endif
         {
             dwError = ERROR_TDNF_FIPS_MODE_FORBIDDEN;
         }
```

2021-11-29 18:52 UTC, merged