BugFix segfault caused due to missing name param
vmware/tdnf pull request #401
Opened 2023-02-16 17:11 UTC by AZaugg

If a repository definition is missing the name parameter the repositroy is later processed and a segfault occurs.

Adding a check to ensure that the repository is not processed in the event that the name parameter is missing.

fixes #400

2023-02-16 17:20 UTC, oliverkurth commented on client/init.c
> +        if ((!pRepo->pszName) || !strcmp(pRepo->pszName, CMDLINE_REPO_NAME) || !pRepo->nEnabled)
I think we should not just ignore and skip it. I think we should check for it in line 238, and bail if NULL.

Maybe we should also add a check right when we read the configuration.

2023-02-21 20:20 UTC, oliverkurth requested changes

2023-02-21 20:20 UTC, oliverkurth commented on client/init.c
> +        if ((!pRepo->pszName) || !strcmp(pRepo->pszName, CMDLINE_REPO_NAME) || !pRepo->nEnabled)
Can you please address this?

2023-02-23 19:59 UTC, oliverkurth commented on client/init.c
> +        if ((!pRepo->pszName) || !strcmp(pRepo->pszName, CMDLINE_REPO_NAME) || !pRepo->nEnabled)
@AZaugg , are going to address my comment? It's fine if not, I can take over.

2023-02-24 23:13 UTC, AZaugg commented
OK, I changed my approach, as the repo stanzas need to be unique, I set the name value to the stanza definition as the default value. I think this is the best of both worlds. Not ignoring it, but not failing if a repo file is missing the name param

2023-02-25 00:58 UTC, oliverkurth commented
> OK, I changed my approach, as the repo stanzas need to be unique, I set the name value to the stanza definition as the default value.

That makes a lot of sense.

2023-02-25 00:58 UTC, oliverkurth approved these changes

2023-02-25 00:59 UTC, merged