Add virtual repo snapshot feature to tdnf
vmware/tdnf pull request #497
Opened 2024-09-20 21:31 UTC by sameluch

This PR adds some functionality built for Azure Linux to tdnf for the broader userbase, virtual repo snapshots. This is the ability to emulate an older snapshot of all enabled repos at a specific timestamp.

Added with this PR is a new config option `snapshottime=<posix_time>` which can be added to tdnf.conf to load as a global version of another added command line option `--snapshottime=<posix_time>`. The snapshot emulates as if the command was run against repos at the given timestamp. All packages which are published to a repo with a timestamp later than the the specified `--snapshottime` will be occluded from the solver and thus not considered for list, install, upgrade, and other commands which hit repositories.

Additionally, if some repos are desired to be not snapshot while executing a given path `--snapshotexcluderepos=<repo_id1>[,<repo_id2>,...]`. Each repo specified in `--snapshotexcluderepos` will NOT have the `--snapshottime` applied to it, if applicable.

2024-09-20 22:09 UTC, oliverkurth commented
Wow, that's a big change. It will take me a while to review this. I have a few question:

What is the use case? Is it just for testing, for example test an upgrade scenario? Or do you want to tag a specific time for a stable build?

Have you considered alternative approaches? For example, wouldn't it be easier to just create a "real" repository with all packages older than the snapshot time (if space is an issue, maybe just use symlinks?). I think this could be done using simple shell scripts, much simpler than this change.

How reliable is the "file" attribute, which is set (I guess) by `createrepo`? Does it use the actual file time stamp, or current time?

Have you thought about implementing this as a plugin? I know the plugin interface would probably need changes for this. But I think the use case is rather limited.

2024-09-30 10:40 UTC, sshedi requested changes
I just did one round of review. Need to understand the logic and usage better.

Some generic comments:
- Avoid sprintf, strcpy and prefer snprintf, strncpy
- Use already available tdnf APIs for memory allocations
- Make functions static if not used outside of file
- Add test cases and try to cover as various scenarios

Please sign the SLA before anything else.

2024-09-30 10:40 UTC, sshedi commented on client/repo.c
> +        if(strncmp(pSetOpt->pszOptName, TDNF_CONF_KEY_SNAPSHOT_TIME, strlen(TDNF_CONF_KEY_SNAPSHOT_TIME)) == 0)
store `strlen(TDNF_CONF_KEY_SNAPSHOT_TIME)` in a variable before entering loop

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    else if (pTracking->nInPackage && !pTracking->nTimeFound)
Checking pTracking->nInPackage for non zero is redundant here.

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    else if (pTracking->nInPackage && !pTracking->nTimeFound)
Checking pTracking->nInPackage for non zero is redundant here.

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    sprintf(*pszElementBuffer, "</%s>", pszElementName);
use snprintf

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    char * pszLintedStr = malloc(nStrToLintLen * sizeof(char));
Use `TDNFAllocateString`

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +checkAndResizeBuffer(char ** ppszCharBuffer, int * pnBufferMaxLen, int nLengthToAdd) {
maybe make this a static function?

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +xmlEscapeCharLinter(const char * pszStringToEscape, char ** ppszDestStr) {
make this a static function

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +                break;
add a default case

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +            strcat(pszLintedStr, pszCharToAdd);
keep track of pszLintedStr index and use it directly. No need to call strcat everytime

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +addElementStartToBuffer(char ** pszElementBuffer, int * nElementBufferMax, const char * pszElementName, const char ** ppszAttrs) {
make this static function

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    sprintf(*pszElementBuffer, "<%s", pszElementName);
use snprintf

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +        pszTempCharBuffer = realloc(*ppszCharBuffer, nTempMaxLen);
Try to make use of `TDNFReAllocateMemory`

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    *pszElementBuffer = malloc(*nElementBufferMax * sizeof(char));
use `TDNFAllocateMemory` or `TDNFAllocateString`

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    if (pszLintedAttrVal)
no need of this if, free handles this now

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    char szNewLineBuffer[2];
`char szNewLineBuffer[2] = {};` this will zero out the whole array

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    if (strcmp(name, "package") == 0 || pTracking->nInPackage)
change the order of this condition check, this might save a strcmp call

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    pTracking->nDepth -= 1;
`pTracking->nDepth--;` makes i easy to read

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    fprintf(pbOutfile, "%s", pszEndElement);
have a wrapper function for this, repeated in many places

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    if (pbOutfile == NULL)
check using IsNullOrEmptyString

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +        if (dwError)
why this check? BAIL_ON_TDNF_TIME_FILTER_ERROR does it already

2024-09-30 10:40 UTC, sshedi commented on solv/tdnfrepo.c
> +    bzero(&pData, sizeof(TDNFFilterData));
please don't mix declarations and function calls

2024-09-30 15:33 UTC, oliverkurth commented
> I just did one round of review. Need to understand the logic and usage better.

Thank you @sshedi . But let's not waste our time until @sameluch has answered my questions. I think there are better ways to achieve the same goal.

2024-10-02 18:06 UTC, sameluch commented
> > I just did one round of review. Need to understand the logic and usage better.
> 
> Thank you @sshedi . But let's not waste our time until @sameluch has answered my questions. I think there are better ways to achieve the same goal.

Hey @oliverkurth, I'll have some answers coming in soon. I was out of town with little internet access so, but back now to work through this larger change. I will sign the CLA as soon as I am able/allowed.
My apologies for opening a large change request and disappearing haha

@sshedi Thanks for the review I will consider the changes as we decide to move forward here and for future development within the tdnf repo.

2024-10-03 20:28 UTC, sameluch commented
> Wow, that's a big change. It will take me a while to review this. I have a few question:
> 
> What is the use case? Is it just for testing, for example test an upgrade scenario? Or do you want to tag a specific time for a stable build?
> 
> Have you considered alternative approaches? For example, wouldn't it be easier to just create a "real" repository with all packages older than the snapshot time (if space is an issue, maybe just use symlinks?). I think this could be done using simple shell scripts, much simpler than this change.
> 
> How reliable is the "file" attribute, which is set (I guess) by `createrepo`? Does it use the actual file time stamp, or current time?
> 
> Have you thought about implementing this as a plugin? I know the plugin interface would probably need changes for this. But I think the use case is rather limited.

@oliverkurth here's some answers for your above questions. Let me know if anything is not particularly clear

Use Case
The main focus of this feature is system stability from the client side without much additional overhead of space or calculation. It gives the option to system maintainers and users to "freeze" their system at a point in time for the purposes of stability. Additionally, should updates ever be required to the snapshot, you can simply just update the timestamp in tdnf.conf or use a new time on --snapshottime within a script or otherwise. The goal is client side customization of a repository snapshot without the maintenance overhead of creation/recreation of a manual repo each time.
This could have many uses such as, A-B testing and image recreation as couple cases the top of my head.

Alternate Approaches I've Considered
- Adding a similar option/function to libsolv which is currently used to read in repository and for package dependency calculation. Though adding this filtering directly to the package manager as an option seemed much more apt for the actual implementation overhead.
- Creation of individual repos for a snapshot given a desired time, this requires much more maintenance by the user or system maintainer. At least for our purposes, this did not seem like the right approach at this time.

The "file" attribute is added by `createrepo` and is present within each `<hash>-primary.xml` file. The time stamps used are those from the files, both the "build" and "file" times are collected this way. The "file" time is when the file was added to the repo, the "build" time is when the file in question was actually generated or built. This has been very reliable across remote repos and my local testing.

I did not consider a plugin implementation of this. Do you have an idea of what the changes might look like in that form? I don't quite see how a plugin interface would fit into this solution?
The actual implementation details of the current feature have the enabled, targeted repo files being temporarily copied and altered such that the data being fed to libsolv are those of the effective timestamp being used to leverage the solver in an intuitive way without the requirement of individual repo management.

2024-10-03 22:32 UTC, oliverkurth commented
Thanks for replying, @sameluch .

I am not convinced that other approaches are more overhead. Here are some ideas:
* creating a separate repo could be simply done with python scripts (or golang if you prefer), which go through the metadata and select just packages with older timestamps. If local, this could be done with symlinks. No impact to tdnf.
* after downloading the primary metadata (`*-primary.xml.gz`), filter it for the timestamps, and replace the original one. This could be done in one of multiple possible ways, for example a plugin, or possibly with a separate script, without impacting tdnf code, or just minimally.
* if this needs to be in tdnf itself, instead of rewriting the metadata file as this change does (IIUC), you can use the `considered` map of the libsolv package pool to filter out packages (looks like you still need to parse the xml separately because apparently the `file` timestamp is not exposed by libsolv, although the `build` time is, see `SOLVABLE_BUILDTIME` in https://github.com/openSUSE/libsolv/blob/master/doc/libsolv-constantids.txt). The `considered` map is used for example (but not only) for the `excludes` feature.

> The "file" time is when the file was added to the repo, 

What does "added" mean? Which time does `createrepo` use here? Its current time, or the file modification time? Something else? Can you point me to the code in `createrepo` that does this?

2024-10-03 23:27 UTC, oliverkurth commented
> It gives the option to system maintainers and users to "freeze" their system at a point in time for the purposes of stability.

What you can do is dump the set of installed packages, to json, like:
```
root [ / ]# tdnf -j list --installed | jq | head
[
  {
    "Name": "bash",
    "Arch": "aarch64",
    "Evr": "5.2-2.ph5",
    "Repo": "@System"
  },
  {
...
```

Then use a script, and install on the target with `tdnf install bash=5.2-2.ph5 ...` etc. So instead of a timestamp, which is pretty unreliable, you use a set of versions.

2025-08-14 18:27 UTC, oliverkurth commented
Closing this. https://github.com/vmware/tdnf/pull/518 should address the feature.

2025-08-14 18:27 UTC, closed without merging